# 
Hola &#x1F600;,

Soy **Hesus Garcia** – **"Soy el único Hesus que conoces (y probablemente conocerás) 🌟"** – Sí, como "Jesús", pero con una H que me hace único. Puede sonar raro, pero créeme, ¡no lo olvidarás! Como tu revisor en Triple-Ten, estoy aquí para guiarte y ayudarte a mejorar tu código. Si algo necesita un ajuste, no hay de qué preocuparse; ¡aquí estoy para hacer que tu trabajo brille con todo su potencial! ✨

Cada vez que encuentre un detalle importante en tu código, te lo señalaré para que puedas corregirlo y así te prepares para un ambiente de trabajo real, donde el líder de tu equipo actuaría de manera similar. Si en algún momento no logras solucionar el problema, te daré más detalles para ayudarte en nuestra próxima oportunidad de revisión.

Es importante que cuando encuentres un comentario, **no los muevas, no los modifiques, ni los borres**.

---

### Formato de Comentarios

Revisaré cuidadosamente cada implementación en tu notebook para asegurar que cumpla con los requisitos y te daré comentarios de acuerdo al siguiente formato:


<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
    
<b>Éxito</b> - ¡Excelente trabajo! Esta parte está bien implementada y contribuye significativamente al análisis de datos o al proyecto. Continúa aplicando estas buenas prácticas en futuras secciones.
    
</div>

<div class="alert alert-block alert-warning">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
    
<b>Atención</b> ⚠️ - Este código está correcto, pero se puede optimizar. Considera implementar mejoras para que sea más eficiente y fácil de leer. Esto fortalecerá la calidad de tu proyecto.
    
</div>

<div class="alert alert-block alert-danger">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
    
<b>A resolver</b> ❗ - Aquí hay un problema o error en el código que es necesario corregir para aprobar esta sección. Por favor, revisa y corrige este punto, ya que es fundamental para la validez del análisis y la precisión de los resultados.
    
</div>

---

Al final de cada revisión, recibirás un **Comentario General del Revisor** que incluirá:

- **Aspectos positivos:** Un resumen de los puntos fuertes de tu proyecto.
- **Áreas de mejora:** Sugerencias sobre aspectos donde puedes mejorar.
- **Temas adicionales para investigar:** Ideas de temas opcionales que puedes explorar por tu cuenta para desarrollar aún más tus habilidades.

Estos temas adicionales no son obligatorios en esta etapa, pero pueden serte útiles para profundizar en el futuro.

---


Esta estructura en viñetas facilita la lectura y comprensión de cada parte del comentario final.

También puedes responderme de la siguiente manera si tienes alguna duda o quieres aclarar algo específico:


<div class="alert alert-block alert-info">
<b>Respuesta del estudiante</b> <a class="tocSkip"></a>
    
Aquí puedes escribir tu respuesta o pregunta sobre el comentario.
    
</div>


**¡Empecemos!** &#x1F680;

### Comentario General del Revisor - 2a iteración

<div class="alert alert-block alert-success">
<b>Comentario del revisor - 2a iteración</b> <a class="tocSkip"></a><br>
¡Felicidades! Tu proyecto está <b>aprobado</b>. El trabajo integra de forma clara el análisis en Python, SQL y Power BI, mostrando una evolución completa desde la exploración de datos hasta la comunicación visual de resultados.

#### Puntos Positivos del código:

* <b>Carga y exploración de datos:</b> Se revisaron correctamente los datasets principales, identificando estructura, tipos de datos, valores nulos y variables relevantes para el análisis. 

* <b>Calidad de datos:</b> Se aplicaron conversiones de fechas, revisión de duplicados, análisis de nulos y validación de variables categóricas, lo que fortalece la confiabilidad del trabajo. 

* <b>Análisis de negocio:</b> Se calcularon métricas clave como revenue, costos, inversión en marketing, profit, ticket promedio, cantidad promedio y producto más vendido, conectando el código con indicadores comerciales. 

* <b>Funnel, cohortes y test estadístico:</b> Se incorporaron consultas SQL y una prueba de proporciones para analizar conversión, retención e impacto de la nueva UI con una interpretación clara de resultados.   

#### Puntos Positivos del dashboard:

* <b>Vista ejecutiva:</b> El dashboard presenta tarjetas KPI claras para revenue, profit, gasto de marketing, ticket promedio y cantidad promedio, facilitando una lectura rápida del desempeño general.

* <b>Visualización temporal:</b> La evolución mensual del revenue y el desempeño acumulado permiten identificar cambios relevantes a lo largo del periodo analizado.

* <b>Análisis por categoría y producto:</b> Las visualizaciones de revenue, profit y volumen de ventas ayudan a distinguir qué categorías y productos concentran mayor impacto comercial.

* <b>Detalle operativo:</b> La tabla de órdenes con filtros y formato condicional aporta profundidad al análisis, permitiendo revisar información granular de productos, costos y rentabilidad.

Has logrado construir un proyecto completo, organizado y orientado a comunicar hallazgos de negocio con herramientas analíticas y visuales.

</div>

<S>


# Comentario General del Revisor - 1a iteración

<div class="alert alert-block alert-warning">
<b>Comentario del revisor - 1a iteración</b> <a class="tocSkip"></a><br>
El proyecto presenta una estructura clara y cubre etapas importantes del análisis, desde la carga y exploración inicial de datos hasta la evaluación del funnel, cohortes y prueba estadística. Se destaca el uso de pandas, SQL y pruebas de proporciones para conectar los resultados con preguntas de negocio.

#### Puntos Positivos:

* **Exploración de datos:** Se revisaron los tres datasets principales y se identificaron tipos de datos, valores nulos y variables categóricas.
* **Calidad de datos:** Se aplicaron conversiones de fechas, revisión de duplicados y validaciones generales sobre los datos.
* **Análisis de funnel:** Se ordenaron las etapas del proceso de compra y se calculó la conversión entre pasos.
* **Retención por cohortes:** Se construyó una consulta SQL para evaluar la actividad de usuarios por semanas desde el registro.
* **Test estadístico:** Se plantearon hipótesis, se aplicó una prueba de proporciones y se interpretó el resultado de forma clara.

**El proyecto aún requiere completar la parte del dashboard para comunicar visualmente los principales hallazgos del análisis. Con esa sección integrada, el trabajo quedará mejor alineado con el objetivo final de convertir los datos en decisiones de negocio.**

</div>

##### Proyecto RappiPlus: de datos a decisiones de negocio

**Introducción**


El objetivo de este proyecto es evaluar el desempeño del servicio **RappiPlus** para apoyar **decisiones de negocio basadas en datos**.

Se trabajan con múltiples datasets del negocio:

- **rappiplus_orders_raw.csv** → información de pedidos, precios, descuentos y revenue  
- **rappiplus_catalog.csv** → costos de productos, categorías y proveedores  
- **rappiplus_marketing_spend.csv** → inversión en marketing por canal y país  
- **events / users / user_activity (SQL)** → comportamiento del usuario dentro de la plataforma  
- **experiment_checkout_ui.csv** → resultados de un experimento A/B en el checkout  

El análisis sigue una lógica clara y progresiva:

1. 🔍 Evaluar si podemos confiar en los datos (calidad de datos en Python) 

2. 💰 Analizar si el negocio es rentable (revenue, costos y profit)  

3. 🛒 Entender dónde se pierden los usuarios (funnel de conversión)  

4. 🔁 Evaluar si los usuarios regresan (retención por cohortes)  

5. 🧪 Validar si los cambios generan impacto (test estadístico)  

6. 📊 Comunicar los resultados (dashboard en BI)  

A lo largo del proyecto, se transforman datos en insights para responder preguntas clave del negocio y proponer **recomendaciones accionables**.

---

## 🔹 Paso 1: Cargar y validar la calidad de los datos

---

### 1.1 Carga de datos y vista rápida

**🎯 Objetivo:** Familiarizarte con la estructura de los datasets del negocio antes de analizarlos.

**Instrucciones:**

- Importa las librerías necesarias
- Carga los archivos:
  - `rappiplus_orders_raw.csv`
  - `rappiplus_catalog.csv`
  - `rappiplus_marketing_spend.csv`
- Guarda los DataFrames en:
  - `orders`, `catalog`, `marketing`
- Explora cada dataset.

---

In [56]:

# importar librerías

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import ttest_ind
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chi2_contingency

In [57]:
# cargar archivos
orders = pd.read_csv('rappiplus_orders_raw.csv') # tu código aquí
catalog = pd.read_csv('rappiplus_catalog.csv') # tu código aquí
marketing = pd.read_csv('rappiplus_marketing_spend.csv') # tu código aquí

In [4]:
# explorar datasets
# tu código aquí
orders.info()
orders

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25100 entries, 0 to 25099
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_pedido           25100 non-null  object
 1   id_usuario          25100 non-null  object
 2   fecha_hora_pedido   25100 non-null  object
 3   pais                24800 non-null  object
 4   dispositivo         25080 non-null  object
 5   fuente_referencia   25070 non-null  object
 6   nombre_producto     25070 non-null  object
 7   categoria_producto  25020 non-null  object
 8   cantidad            25050 non-null  float64
 9   precio_unitario     25050 non-null  float64
 10  monto_descuento     25050 non-null  float64
 11  monto_total         25100 non-null  float64
dtypes: float64(4), object(8)
memory usage: 2.3+ MB

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
0,order_0,user_6993,2025-05-22,Argentina,desktop,organic,Jacket-Winter-M,Moda,2.0,332.69,0.0,665.37
1,order_1,user_1329,2025-06-15,Mexico,desktop,paid_search,Tablet-Standard-64GB,Electronica,1.0,176.86,5.0,171.86
2,order_2,user_3194,2025-05-02,Argentina,desktop,social,Blender-XL-Red,Hogar,2.0,102.99,10.0,195.99
3,order_3,user_4510,2025-06-09,Colombia,mobile,social,Tablet-Standard-64GB,Electronica,1.0,257.87,15.0,242.87
4,order_4,user_5044,2025-03-30,Argentina,desktop,paid_search,Blender-XL-Red,Hogar,1.0,336.28,0.0,336.28
...,...,...,...,...,...,...,...,...,...,...,...,...
25095,order_3913,user_380,2025-02-18,Argentina,desktop,paid_search,Phone-Pro-128GB,Electronica,1.0,82.28,0.0,82.28
25096,order_23405,user_7833,2025-04-04,Colombia,mobile,paid_search,Phone-Pro-128GB,Electronica,2.0,99.25,5.0,193.50
25097,order_5615,user_5417,2025-05-13,Colombia,desktop,social,Blender-XL-Red,Hogar,2.0,450.35,5.0,895.69
25098,order_812,user_1530,2025-03-31,Argentina,desktop,organic,Tablet-Standard-64GB,Electronica,1.0,167.32,10.0,157.32
25099,order_1361,user_507,2025-06-27,Mexico,desktop,paid_search,Laptop-Gaming-16GB,Electronica,2.0,239.61,0.0,479.22

In [5]:
catalog.info()
catalog

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nombre_producto     7 non-null      object
 1   categoria_producto  7 non-null      object
 2   costo_unitario      7 non-null      float64
 3   proveedor           7 non-null      object
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes

,nombre_producto,categoria_producto,costo_unitario,proveedor
0,Laptop-Gaming-16GB,Electrónica,280.68,"Fuller, Pena and Myers"
1,Phone-Pro-128GB,Electrónica,10.12,King Ltd
2,Tablet-Standard-64GB,Electrónica,25.21,Bowers LLC
3,Blender-XL-Red,Hogar,176.64,Long-Reid
4,Vacuum-Pro-Black,Hogar,16.60,"Rivera, Carr and Finley"
5,Sneakers-Urban-42,Moda,17.21,Greene-Smith
6,Jacket-Winter-M,Moda,189.31,Mcmillan-Rhodes

In [6]:
marketing.info()
marketing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1620 entries, 0 to 1619
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1620 non-null   object
 1   pais        1620 non-null   object
 2   id_campaña  1620 non-null   object
 3   canal       1519 non-null   object
 4   gasto       1620 non-null   float64
dtypes: float64(1), object(4)
memory usage: 63.4+ KB

           fecha       pais             id_campaña        canal    gasto
0     2025-01-01     Mexico         organic_Mexico      organic  2446.25
1     2025-01-01     Mexico     paid_search_Mexico  paid_search  2704.34
2     2025-01-01     Mexico          social_Mexico       social  2045.01
3     2025-01-01   Colombia       organic_Colombia      organic  2597.21
4     2025-01-01   Colombia   paid_search_Colombia  paid_search  1771.40
...          ...        ...                    ...          ...      ...
1615  2025-06-29   Colombia   paid_search_Colombia  paid_search   550.50
1616  2025-06-29   Colombia        social_Colombia       social   999.15
1617  2025-06-29  Argentina      organic_Argentina      organic  1267.14
1618  2025-06-29  Argentina  paid_search_Argentina  paid_search  2719.41
1619  2025-06-29  Argentina       social_Argentina       social   621.01

[1620 rows x 5 columns]

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - La carga de los tres datasets se concretó correctamente y la exploración inicial permite identificar estructura, tipos de datos y valores faltantes de forma clara.
</div>

---

### Revisión y calidad de datos

**🎯 Objetivo:** Detectar y corregir problemas en los datos que puedan afectar el análisis de revenue, costos y rentabilidad.

Se revisan los 3 datasets
- Validar y convertir fechas al formato correcto  
- Revisar variables numéricas (sin negativos o ceros inválidos)  
- Verificar consistencia de montos  
- Eliminar duplicados  
- Revisar variables categóricas 

---

In [7]:
# tu código aquí
# Validar y convertir fechas al formato correcto hay filas con valores faltantes 
marketing['fecha'] = pd.to_datetime(marketing['fecha'], errors= 'coerce')

In [8]:
# Revisar si hay errores
marketing[marketing['fecha'].isna()]
marketing.info()
marketing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1620 entries, 0 to 1619
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1620 non-null   datetime64[ns]
 1   pais        1620 non-null   object
 2   id_campaña  1620 non-null   object
 3   canal       1519 non-null   object
 4   gasto       1620 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 63.4+ KB

          fecha       pais             id_campaña        canal    gasto
0    2025-01-01     Mexico         organic_Mexico      organic  2446.25
1    2025-01-01     Mexico     paid_search_Mexico  paid_search  2704.34
2    2025-01-01     Mexico          social_Mexico       social  2045.01
3    2025-01-01   Colombia       organic_Colombia      organic  2597.21
4    2025-01-01   Colombia   paid_search_Colombia  paid_search  1771.40
...         ...        ...                    ...          ...      ...
1615 2025-06-29   Colombia   paid_search_Colombia  paid_search   550.50
1616 2025-06-29   Colombia        social_Colombia       social   999.15
1617 2025-06-29  Argentina      organic_Argentina      organic  1267.14
1618 2025-06-29  Argentina  paid_search_Argentina  paid_search  2719.41
1619 2025-06-29  Argentina       social_Argentina       social   621.01

[1620 rows x 5 columns]

In [58]:
# orders convertir a fecha hora 
orders['fecha_hora_pedido'] = pd.to_datetime(orders['fecha_hora_pedido'], errors='coerce')
orders.head(5) # no se cuenta con alguna columna que nos pueda indicar la hora de la fecha del pedido

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
0,order_0,user_6993,2025-05-22,Argentina,desktop,organic,Jacket-Winter-M,Moda,2.0,332.69,0.0,665.37
1,order_1,user_1329,2025-06-15,Mexico,desktop,paid_search,Tablet-Standard-64GB,Electronica,1.0,176.86,5.0,171.86
2,order_2,user_3194,2025-05-02,Argentina,desktop,social,Blender-XL-Red,Hogar,2.0,102.99,10.0,195.99
3,order_3,user_4510,2025-06-09,Colombia,mobile,social,Tablet-Standard-64GB,Electronica,1.0,257.87,15.0,242.87
4,order_4,user_5044,2025-03-30,Argentina,desktop,paid_search,Blender-XL-Red,Hogar,1.0,336.28,0.0,336.28

In [10]:
# Revisar variables numéricas (sin negativos o ceros inválidos)
# Hacer deteccion de nulos 
marketing['gasto'].isna().sum()

0

In [11]:
# Hacer deteccion de negativos o ceros invalidos
marketing[marketing['gasto']<=0]
marketing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1620 entries, 0 to 1619
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1620 non-null   datetime64[ns]
 1   pais        1620 non-null   object
 2   id_campaña  1620 non-null   object
 3   canal       1519 non-null   object
 4   gasto       1620 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 63.4+ KB

In [12]:
# Verificar consistencia de montos
# Todos los valores deben ser positivos
marketing[marketing['gasto'] <=0]

Empty DataFrame
Columns: [fecha, pais, id_campaña, canal, gasto]
Index: []

In [13]:
#Revisar valores nulos en dataset marketing
marketing[marketing['gasto'].isna()]

Empty DataFrame
Columns: [fecha, pais, id_campaña, canal, gasto]
Index: []

In [14]:
# Revisar el REVENUE = precio_unitario por  cantidad en el dataset orders
orders['calc_monto_total'] = orders['precio_unitario'] * orders['cantidad']

# Comparar con revenue reportado
orders[orders['calc_monto_total'] != orders['monto_total']]

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total,calc_monto_total
0,order_0,user_6993,2025-05-22,Argentina,desktop,organic,Jacket-Winter-M,Moda,2.0,332.69,0.0,665.37,665.38
1,order_1,user_1329,2025-06-15,Mexico,desktop,paid_search,Tablet-Standard-64GB,Electronica,1.0,176.86,5.0,171.86,176.86
2,order_2,user_3194,2025-05-02,Argentina,desktop,social,Blender-XL-Red,Hogar,2.0,102.99,10.0,195.99,205.98
3,order_3,user_4510,2025-06-09,Colombia,mobile,social,Tablet-Standard-64GB,Electronica,1.0,257.87,15.0,242.87,257.87
6,order_6,user_2802,2025-03-15,Colombia,mobile,organic,Blender-XL-Red,Hogar,2.0,163.59,0.0,327.19,327.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25091,order_21779,user_3295,2025-05-11,Argentina,desktop,organic,Laptop-Gaming-16GB,Electronica,2.0,338.67,0.0,677.33,677.34
25092,order_24367,user_434,2025-03-22,Colombia,desktop,organic,Laptop-Gaming-16GB,Electronica,2.0,216.57,15.0,418.13,433.14
25096,order_23405,user_7833,2025-04-04,Colombia,mobile,paid_search,Phone-Pro-128GB,Electronica,2.0,99.25,5.0,193.50,198.50
25097,order_5615,user_5417,2025-05-13,Colombia,desktop,social,Blender-XL-Red,Hogar,2.0,450.35,5.0,895.69,900.70
25098,order_812,user_1530,2025-03-31,Argentina,desktop,organic,Tablet-Standard-64GB,Electronica,1.0,167.32,10.0,157.32,167.32

In [15]:
# Eliminar duplicados de los 3 datasets
orders.drop_duplicates(inplace=True)
catalog.drop_duplicates(inplace=True)
marketing.drop_duplicates(inplace=True)

In [16]:
orders.info()
catalog.info()
marketing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25000 entries, 0 to 24999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_pedido           25000 non-null  object
 1   id_usuario          25000 non-null  object
 2   fecha_hora_pedido   25000 non-null  datetime64[ns]
 3   pais                24700 non-null  object
 4   dispositivo         24980 non-null  object
 5   fuente_referencia   24970 non-null  object
 6   nombre_producto     24970 non-null  object
 7   categoria_producto  24920 non-null  object
 8   cantidad            24950 non-null  float64
 9   precio_unitario     24950 non-null  float64
 10  monto_descuento     24950 non-null  float64
 11  monto_total         25000 non-null  float64
 12  calc_monto_total    24950 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(7)
memory usage: 2.7+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nombre_producto     7 non-null      object
 1   categoria_producto  7 non-null      object
 2   costo_unitario      7 non-null      float64
 3   proveedor           7 non-null      object
dtypes: float64(1), object(3)
memory usage: 280.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1620 entries, 0 to 1619
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1620 non-null   datetime64[ns]
 1   pais        1620 non-null   object
 2   id_campaña  1620 non-null   object
 3   canal       1519 non-null   object
 4   gasto       1620 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 75.9+ KB

In [17]:
# Revisar Variables Categoricas
catalog['categoria_producto'].unique()

array(['Electrónica', 'Hogar', 'Moda'], dtype=object)

In [21]:
# Dataset marketing se revisan errores de captura en las columnas canal y pais
marketing['canal'].unique()

array(['organic', 'paid_search', 'social', nan], dtype=object)

In [23]:
marketing[marketing['canal'].isna()]

         fecha       pais             id_campaña canal    gasto
98  2025-01-11  Argentina       social_Argentina   NaN   849.70
99  2025-01-12     Mexico         organic_Mexico   NaN  2033.56
100 2025-01-12     Mexico     paid_search_Mexico   NaN  1260.65
101 2025-01-12     Mexico          social_Mexico   NaN  1660.90
102 2025-01-12   Colombia       organic_Colombia   NaN  1819.27
..         ...        ...                    ...   ...      ...
194 2025-01-22   Colombia        social_Colombia   NaN   772.46
195 2025-01-22  Argentina      organic_Argentina   NaN  1562.61
196 2025-01-22  Argentina  paid_search_Argentina   NaN   644.34
197 2025-01-22  Argentina       social_Argentina   NaN  2544.66
198 2025-01-23     Mexico         organic_Mexico   NaN  2977.84

[101 rows x 5 columns]

In [59]:
# Se revisan errores de captura en las columnas pais,dispositivo,funte_referencia,categoria_producto del dataset orders
orders['pais'].unique()

array(['Argentina', 'Mexico', 'Colombia', 'mexico', 'colombia',
       'argentina', nan], dtype=object)

In [30]:
orders['dispositivo'].unique()

array(['desktop', 'mobile', nan], dtype=object)

In [31]:
orders['fuente_referencia'].unique()

array(['organic', 'paid_search', 'social', nan], dtype=object)

In [32]:
orders['categoria_producto'].unique()

array(['Moda', 'Electronica', 'Hogar', nan], dtype=object)

In [34]:
def quality_report(df):
    print("----- REPORTE DE CALIDAD -----")
    print("Filas:", len(df))
    print("\nValores nulos:")
    print(df.isna().sum())
    print("\nDuplicados:", df.duplicated().sum())
    print("\nTipos de datos:")
    print(df.dtypes)
    print("\nValores categóricos:")
    for col in df.select_dtypes(include='object').columns:
        print(f"{col}: {df[col].unique()[:10]}")

quality_report(marketing)
quality_report(catalog)
quality_report(orders)

----- REPORTE DE CALIDAD -----
Filas: 1620

Valores nulos:
fecha           0
pais            0
id_campaña      0
canal         101
gasto           0
dtype: int64

Duplicados: 0

Tipos de datos:
fecha         datetime64[ns]
pais                  object
id_campaña            object
canal                 object
gasto                float64
dtype: object

Valores categóricos:
pais: ['Mexico' 'Colombia' 'Argentina']
id_campaña: ['organic_Mexico' 'paid_search_Mexico' 'social_Mexico' 'organic_Colombia'
 'paid_search_Colombia' 'social_Colombia' 'organic_Argentina'
 'paid_search_Argentina' 'social_Argentina']
canal: ['organic' 'paid_search' 'social' nan]
----- REPORTE DE CALIDAD -----
Filas: 7

Valores nulos:
nombre_producto       0
categoria_producto    0
costo_unitario        0
proveedor             0
dtype: int64

Duplicados: 0

Tipos de datos:
nombre_producto        object
categoria_producto     object
costo_unitario        float64
proveedor              object
dtype: object

Valores categóricos:
nombre_producto: ['Laptop-Gaming-16GB' 'Phone-Pro-128GB' 'Tablet-Standard-64GB'
 'Blender-XL-Red' 'Vacuum-Pro-Black' 'Sneakers-Urban-42' 'Jacket-Winter-M']
categoria_producto: ['Electrónica' 'Hogar' 'Moda']
proveedor: ['Fuller, Pena and Myers' 'King Ltd' 'Bowers LLC' 'Long-Reid'
 'Rivera, Carr and Finley' 'Greene-Smith' 'Mcmillan-Rhodes']
----- REPORTE DE CALIDAD -----
Filas: 25000

Valores nulos:
id_pedido               0
id_usuario              0
fecha_hora_pedido       0
pais                  300
dispositivo            20
fuente_referencia      30
nombre_producto        30
categoria_producto     80
cantidad               50
precio_unitario        50
monto_descuento        50
monto_total             0
calc_monto_total       50
dtype: int64

Duplicados: 0

Tipos de datos:
id_pedido                     object
id_usuario                    object
fecha_hora_pedido     datetime64[ns]
pais                          object
dispositivo                   object
fuente_referencia             object
nombre_producto               object
categoria_producto            object
cantidad                     float64
precio_unitario              float64
monto_descuento              float64
monto_total                  float64
calc_monto_total             float64
dtype: object

Valores categóricos:
id_pedido: ['order_0' 'order_1' 'order_2' 'order_3' 'order_4' 'order_5' 'order_6'
 'order_7' 'order_8' 'order_9']
id_usuario: ['user_6993' 'user_1329' 'user_3194' 'user_4510' 'user_5044' 'user_2792'
 'user_2802' 'user_1083' 'user_2352' 'user_7001']
pais: ['Argentina' 'Mexico' 'Colombia' 'mexico' 'colombia' 'argentina' nan]
dispositivo: ['desktop' 'mobile' nan]
fuente_referencia: ['organic' 'paid_search' 'social' nan]
nombre_producto: ['Jacket-Winter-M' 'Tablet-Standard-64GB' 'Blender-XL-Red'
 'Laptop-Gaming-16GB' 'Sneakers-Urban-42' 'Phone-Pro-128GB'
 'Vacuum-Pro-Black' nan]
categoria_producto: ['Moda' 'Electronica' 'Hogar' nan]

---
**📦 Exportación**: Una vez finalizada la limpieza, se exportan los datasets para utilizarlos en la última etapa del proyecto.

In [35]:
# exportar datasets
orders.to_csv('orders_clean.csv', index=False)
catalog.to_csv('catalog_clean.csv', index=False)
marketing.to_csv('marketing_clean.csv', index=False)

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - La revisión de calidad se desarrolló de manera ordenada, cubriendo fechas, duplicados, nulos, variables categóricas y exportación de los datasets limpios. 
</div>

---

## 🔹 Paso 2: Analizar si el negocio es rentable

### 2.1 Cálculo de KPIs principales

**🎯 Objetivo:** Calcular los indicadores clave del negocio para evaluar ingresos, costos y rentabilidad.

Se usan los 3 datasets (`orders`, `catalog`, `marketing_spend`):

**📊 Parte 1: Rentabilidad del negocio**
- ¿Cuál es el ingreso total (revenue)? 
- ¿Cuál es el costo total? 
- ¿Cuánto se ha invertido en marketing? 
- ¿El negocio es rentable? (calcular profit)  

---

**📈 Parte 2: Comportamiento de ventas**
- ¿Cuál es el ticket promedio por orden? 
- ¿Cuál es la cantidad promedio de productos por orden? 
- ¿Cuál es el producto más vendido?
- ¿Cuánto se ha gastado en marketing por canal?

 ## Rentabilidad del negocio

In [36]:
# tu código aquí
# cargar archivos
orders = pd.read_csv('rappiplus_orders_raw.csv') # tu código aquí
catalog = pd.read_csv('rappiplus_catalog.csv') # tu código aquí
marketing = pd.read_csv('rappiplus_marketing_spend.csv') # tu código aquí

In [53]:
# Ingreso Total (Revenue) se tiene que unir dos tablas para obtener el costo_unitario orders y catalog ya que orders no cuenta con la fila 
orders_full = orders.merge(catalog, on=['nombre_producto', 'categoria_producto'], how='left')

In [55]:
# Calcular ingreso total 
orders_full['revenue'] = orders_full['cantidad']* orders_full['costo_unitario']

In [57]:
# Ingreso Total 
Ingreso_Total = orders_full['revenue'].sum()
Ingreso_Total 
print(f"El negocio generó ${Ingreso_Total:,.2f} en ingresos totales durante el periodo analizado.")

El negocio generó $2,514,163.41 en ingresos totales durante el periodo analizado.

In [49]:
orders_full

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total,costo_unitario,proveedor,revenue
0,order_0,user_6993,2025-05-22,Argentina,desktop,organic,Jacket-Winter-M,Moda,2.0,332.69,0.0,665.37,189.31,Mcmillan-Rhodes,378.62
1,order_1,user_1329,2025-06-15,Mexico,desktop,paid_search,Tablet-Standard-64GB,Electronica,1.0,176.86,5.0,171.86,NaN,NaN,NaN
2,order_2,user_3194,2025-05-02,Argentina,desktop,social,Blender-XL-Red,Hogar,2.0,102.99,10.0,195.99,176.64,Long-Reid,353.28
3,order_3,user_4510,2025-06-09,Colombia,mobile,social,Tablet-Standard-64GB,Electronica,1.0,257.87,15.0,242.87,NaN,NaN,NaN
4,order_4,user_5044,2025-03-30,Argentina,desktop,paid_search,Blender-XL-Red,Hogar,1.0,336.28,0.0,336.28,176.64,Long-Reid,176.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25095,order_3913,user_380,2025-02-18,Argentina,desktop,paid_search,Phone-Pro-128GB,Electronica,1.0,82.28,0.0,82.28,NaN,NaN,NaN
25096,order_23405,user_7833,2025-04-04,Colombia,mobile,paid_search,Phone-Pro-128GB,Electronica,2.0,99.25,5.0,193.50,NaN,NaN,NaN
25097,order_5615,user_5417,2025-05-13,Colombia,desktop,social,Blender-XL-Red,Hogar,2.0,450.35,5.0,895.69,176.64,Long-Reid,353.28
25098,order_812,user_1530,2025-03-31,Argentina,desktop,organic,Tablet-Standard-64GB,Electronica,1.0,167.32,10.0,157.32,NaN,NaN,NaN
25099,order_1361,user_507,2025-06-27,Mexico,desktop,paid_search,Laptop-Gaming-16GB,Electronica,2.0,239.61,0.0,479.22,NaN,NaN,NaN

In [62]:
# Costo Total del negocio
Costo_Total = (orders_full['cantidad']* orders_full['costo_unitario']).sum()
Costo_Total
print(f"El costo total de los productos vendidos fue de ${Costo_Total:,.2f}")

El costo total de los productos vendidos fue de $2,514,163.41

In [65]:
# Inversion Total en marketing
total_marketing_spend = marketing['gasto'].sum()
total_marketing_spend
print(f"La inversión total en marketing fue de ${total_marketing_spend:,.2f}")

La inversión total en marketing fue de $2,871,843.53

In [68]:
# ¿El negocio es rentable? (Profit)
profit = Ingreso_Total - Costo_Total - total_marketing_spend
profit
print(f"El negocio no es rentable; presenta una pérdida de ${profit:,.2f}")

El negocio no es rentable; presenta una pérdida de $-2,871,843.53

 ## Comportamiento de ventas

In [72]:
# Ticket promedio por orden
ticket_promedio = Ingreso_Total / orders_full['id_pedido'].nunique()
ticket_promedio
print(f"El ticket promedio por orden es de ${ticket_promedio:,.2f}")

El ticket promedio por orden es de $100.57

In [75]:
# Cantidad Promedio de productos por Order
cantidad_promedio = orders_full['cantidad'].mean()
cantidad_promedio
print(f"En promedio, los clientes compran {cantidad_promedio:,.2f}  productos por orden.")

En promedio, los clientes compran 7.09  productos por orden.

In [79]:
# Producto más vendido
producto_mas_vendido = orders_full.groupby('nombre_producto')['cantidad'].sum().sort_values(ascending=False).head(1)
producto_mas_vendido

nombre_producto
Laptop-Gaming-16GB    144219.0
Name: cantidad, dtype: float64

In [80]:
# Gasto Marketing por Canal
gasto_por_canal = marketing.groupby('canal')['gasto'].sum()
gasto_por_canal

canal
organic        913533.01
paid_search    863088.21
social         918043.21
Name: gasto, dtype: float64

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - La sección avanza en el cálculo de métricas clave de rentabilidad y comportamiento de ventas, integrando datos de pedidos, catálogo y marketing para conectar los resultados con el desempeño del negocio.
</div>

## 🔹 Paso 3: Entender dónde se pierden los usuarios (funnel de conversión)

**🎯 Objetivo:** Analizar el comportamiento de los usuarios para identificar en qué etapa del proceso se pierden.


⚙️**Conexión a la base de datos**:  
Se ejecuta la línea de configuración para conectar con la base de datos y aplicar consultas SQL en la tabla **events**.

---

**📊 Parte 1: Construcción del funnel**
- ¿Cuántos usuarios llegan a cada etapa del funnel?  
- Se calcula el número de usuarios únicos por `nombre_evento`  
- Se ordenan los eventos según el flujo del usuario  

---

**📉 Parte 2: Análisis de conversión**
- Se calcula la tasa de conversión entre cada paso del funnel  
- Se identifica en qué etapa se pierde la mayor cantidad de usuarios  
- ¿Cuál es la tasa de conversión final?
---

In [1]:

import pandas as pd
from sqlalchemy import create_engine

# ======================
# Conexión (NO modificar)
# ======================
db_config = {
    'user': 'practicum_student',
    'pwd': 'QnmDH8Sc2TQLvy2G3Vvh7',
    'host': 'yp-trainers-practicum.cluster-czs0gxyx2d8w.us-east-1.rds.amazonaws.com',
    'port': 5432,
    'db': 'data-analyst-production-db-en'
}

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(
    db_config['user'],
    db_config['pwd'],
    db_config['host'],
    db_config['port'],
    db_config['db']
)

engine = create_engine(connection_string, connect_args={'sslmode':'require'})

In [8]:
# Explorar tabla events
# =========================
query_events = '''
SELECT *
FROM events
LIMIT 10;
'''
events = pd.read_sql(query_events, con=engine)
events.head(10)

,id_usuario,id_sesion,nombre_evento,timestamp_evento,pais,dispositivo,fuente_referencia,categoria_producto
0,user_6772,6a97f2af-32ae-4186-8c92-04025be1a27b,first_visit,2025-05-17,Colombia,desktop,organic,Moda
1,user_5883,369b767c-1c33-4b2f-a652-c7c0ef92cfc9,add_to_cart,2025-02-23,Mexico,mobile,social,Hogar
2,user_5946,60039041-e78b-474c-87b3-c0b7e9c30708,add_payment_info,2025-05-15,Colombia,desktop,social,Electronica
3,user_827,18252a64-f389-4ef7-9e58-dadad4a3491e,purchase,2025-03-31,Mexico,mobile,social,Moda
4,user_2361,221b364e-cdc5-4668-b698-18d5ba849a67,first_visit,2025-01-22,Argentina,desktop,paid_search,Electronica
5,user_4402,0892643c-f80d-4eb4-9ca8-3638b16c6ed4,begin_checkout,2025-04-21,Argentina,desktop,paid_search,Hogar
6,user_767,0005a13c-3c1f-496b-a26a-f3c282f19e13,begin_checkout,2025-03-01,Mexico,mobile,social,Electronica
7,user_2694,b07336e6-1207-4ee1-82e3-1fa7fbd194e3,add_payment_info,2025-03-22,Colombia,desktop,organic,Hogar
8,user_7209,f42bd8cd-aff2-4b7e-94e2-d4d885d23afc,add_to_cart,2025-05-07,Mexico,desktop,organic,Moda
9,user_1788,abf1af77-e96b-4490-9efb-3fa5d8271ad4,add_to_cart,2025-05-13,Argentina,desktop,organic,Moda

In [13]:
# PARTE 1: Totales del funnel
# ======================

query_totals = '''
SELECT 
    nombre_evento,
    COUNT(DISTINCT id_usuario) AS usuarios_unicos
FROM events 
GROUP BY nombre_evento
ORDER BY nombre_evento;
'''

totals = pd.read_sql(query_totals, con=engine)
totals

      nombre_evento  usuarios_unicos
0  add_payment_info             6250
1       add_to_cart             7634
2    begin_checkout             7208
3       first_visit             7796
4          purchase             6240
5       select_item             7582

In [20]:
orden_del_funnel = [
    'first_visit',
    'select_item',
    'add_to_cart',
    'begin_checkout',
    'add_payment_info',
    'purchase']

totals['orden'] = totals['nombre_evento'].apply(lambda x: orden_del_funnel.index(x))
totals = totals.sort_values('orden')
totals

      nombre_evento  usuarios_unicos  orden
3       first_visit             7796      0
5       select_item             7582      1
1       add_to_cart             7634      2
2    begin_checkout             7208      3
0  add_payment_info             6250      4
4          purchase             6240      5

In [22]:
# PARTE 2: Conversiones
# ======================

query_conversion = '''

'''

conversion = pd.read_sql(query_conversion, con=engine)
conversion

In [35]:
# Calcular Tasa de conversion
totals['conversion'] = totals['usuarios_unicos'] / totals['usuarios_unicos'].shift(1).round()
totals
totals['conversion_pct'] = (totals['conversion'] * 100).round(2)
totals

,nombre_evento,usuarios_unicos,orden,conversion,conversion_pct,perdida
3,first_visit,7796,0,NaN,NaN,NaN
5,select_item,7582,1,0.972550,97.26,214.0
1,add_to_cart,7634,2,1.006858,100.69,-52.0
2,begin_checkout,7208,3,0.944197,94.42,426.0
0,add_payment_info,6250,4,0.867092,86.71,958.0
4,purchase,6240,5,0.998400,99.84,10.0

In [37]:
# Calcular la perdida de usauiros entre pasos 
totals['perdida'] = totals['usuarios_unicos'].shift(1) - totals['usuarios_unicos']
totals

,nombre_evento,usuarios_unicos,orden,conversion,conversion_pct,perdida
3,first_visit,7796,0,NaN,NaN,NaN
5,select_item,7582,1,0.972550,97.26,214.0
1,add_to_cart,7634,2,1.006858,100.69,-52.0
2,begin_checkout,7208,3,0.944197,94.42,426.0
0,add_payment_info,6250,4,0.867092,86.71,958.0
4,purchase,6240,5,0.998400,99.84,10.0

In [39]:
# Etapa conmayor perdida
etapa_critica = totals.loc[totals['perdida'].idxmax()]
etapa_critica

nombre_evento      add_payment_info
usuarios_unicos                6250
orden                             4
conversion                 0.867092
conversion_pct                86.71
perdida                       958.0
Name: 0, dtype: object

In [48]:
# Calcular la conversion fianl de FUNNEL 
conversion_final = totals['usuarios_unicos'].iloc[-1] / totals['usuarios_unicos'].iloc[0]
conversion_final
conversion_pct = f"{round(conversion_final * 100, 2)}%"
conversion_pct

'80.04%'

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - El análisis del funnel queda bien estructurado al ordenar las etapas del usuario, calcular conversiones entre pasos e identificar el punto principal de pérdida dentro del proceso de compra.
</div>

## 🔹 Paso 4: Evaluar si los usuarios regresan (retención por cohortes)

**🎯 Objetivo:** Analizar la retención de usuarios para entender si regresan después de registrarse.

**Tablas**

- `users` 
- `user_activity` 

---
1. Se identifica la cohorte de cada usuario según el **mes de registro**.


2. Se calcula la retención semanal: cuántos usuarios **se mantienen activos** en cada semana desde su registro.
   - `retenido_w1`: usuarios activos en la semana 1  
   - `retenido_w2`: usuarios activos en la semana 2  
   - `retenido_w3`: usuarios activos en la semana 3  


3. Se calcula el porcentaje de retención para cada semana, dividiendo los usuarios retenidos entre los clientes iniciales de la cohorte:  
   - `semana_1`: porcentaje de usuarios retenidos en la semana 1  
   - `semana_2`: porcentaje de usuarios retenidos en la semana 2  
   - `semana_3`: porcentaje de usuarios retenidos en la semana 3  

Se revisa que la columna de fecha esté en formato correcto (`DATE`).  
Se realiza la conversión usando: `CAST(fecha_registro AS DATE)`

In [49]:
# Explorar tabla users
# =========================
query_users = '''
SELECT *
FROM users;
'''
users = pd.read_sql(query_users, con=engine)
users.head(3)

  id_usuario fecha_registro       país dispositivo tipo_plan
0     user_0     2025-01-29     Mexico      mobile      free
1     user_1     2025-01-07     Mexico      mobile      free
2     user_2     2025-03-12  Argentina      mobile      free

In [51]:
# Explorar tabla user_activity
# =========================
query_user_activity = '''
SELECT *
FROM user_activity;
'''
user_activity = pd.read_sql(query_user_activity, con=engine)
user_activity.head(3)

  id_usuario fecha_actividad  dias_despues_registro  activo
0     user_0      2025-02-05                      7       0
1     user_0      2025-02-12                     14       1
2     user_0      2025-02-19                     21       1

In [72]:
# Retención por cohortes
# ======================

query_cohort_retention_final = '''
WITH cohortes AS (
    SELECT
        id_usuario,
        DATE_TRUNC('month', fecha_registro::date) AS cohorte
    FROM users
),

actividad AS (
    SELECT
        ua.id_usuario,
        c.cohorte,
        ua.fecha_actividad::date AS fecha_actividad,
        FLOOR(
            EXTRACT(DAY FROM AGE(ua.fecha_actividad::date, u.fecha_registro::date)) / 7
        ) + 1 AS semana
    FROM user_activity ua
    JOIN users u ON ua.id_usuario = u.id_usuario
    JOIN cohortes c ON ua.id_usuario = c.id_usuario
),

retencion AS (
    SELECT
        cohorte,
        semana,
        COUNT(DISTINCT id_usuario) AS usuarios_retenidos
    FROM actividad
    WHERE semana BETWEEN 1 AND 3
    GROUP BY cohorte, semana
),

usuarios_iniciales AS (
    SELECT
        cohorte,
        COUNT(*) AS usuarios_iniciales
    FROM cohortes
    GROUP BY cohorte
)

SELECT
    r.cohorte,
    r.semana,
    r.usuarios_retenidos,
    u.usuarios_iniciales,
    ROUND(r.usuarios_retenidos * 100.0 / u.usuarios_iniciales, 2) AS retencion_pct
FROM retencion r
JOIN usuarios_iniciales u USING (cohorte)
ORDER BY cohorte, semana;


'''



# Ejecutar la consulta
cohorte_final = pd.read_sql(query_cohort_retention_final, con=engine)
cohorte_final

,cohorte,semana,usuarios_retenidos,usuarios_iniciales,retencion_pct
0,2025-01-01 00:00:00+00:00,2.0,1627,1627,100.0
1,2025-01-01 00:00:00+00:00,3.0,1627,1627,100.0
2,2025-02-01 00:00:00+00:00,1.0,1444,1444,100.0
3,2025-02-01 00:00:00+00:00,2.0,1444,1444,100.0
4,2025-02-01 00:00:00+00:00,3.0,1444,1444,100.0
5,2025-03-01 00:00:00+00:00,2.0,1636,1636,100.0
6,2025-03-01 00:00:00+00:00,3.0,1636,1636,100.0
7,2025-04-01 00:00:00+00:00,2.0,1606,1606,100.0
8,2025-04-01 00:00:00+00:00,3.0,1606,1606,100.0
9,2025-05-01 00:00:00+00:00,2.0,1687,1687,100.0
10,2025-05-01 00:00:00+00:00,3.0,1687,1687,100.0

In [69]:
import pandas as pd

pd.read_sql("SELECT VERSION();", con=engine)

                                             version
0  PostgreSQL 14.20 on aarch64-unknown-linux-gnu,...

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - La sección construye el análisis de cohortes con una consulta SQL organizada, relacionando usuarios y actividad para medir la retención semanal de forma clara y orientada al comportamiento de los clientes.
</div>

---

## 🔹 Paso 5: Validar si los cambios generan impacto (test estadístico)

🎯 **Objetivo:** Evaluar si la modificación en la UI del checkout impacta la **tasa de conversión de compra**.

---

1. **Analizar el dataset** `experiment_checkout_ui.csv` para identificar la métrica principal **conversion**.
   - La métrica **conversion** es 1 si el usuario completó la compra, 0 si no.    
2. **Plantear la hipótesis estadística**     
3. **Aplicar el test estadístico adecuado** 
4. **Interpretar el resultado**

---
Hipótesis estadística
   - **H₀ (Hipótesis nula):** ...
   - **H₁ (Hipótesis alternativa):** ...
   
**Test estadístico:** ...  
**Nivel de significancia alpha:** ...

In [73]:
# tu código aquí
# importar librerías

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import ttest_ind
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chi2_contingency

In [80]:
df = pd.read_csv('experiment_checkout_ui.csv')
df

,id_usuario,variante,convirtio,dispositivo,pais,duracion_sesion,timestamp
0,exp_user_0,tratamiento,0,mobile,Argentina,114.41,2025-03-28
1,exp_user_1,tratamiento,0,desktop,Mexico,170.03,2025-01-15
2,exp_user_2,control,1,mobile,Colombia,140.21,2025-03-18
3,exp_user_3,tratamiento,0,mobile,Colombia,151.45,2025-06-03
4,exp_user_4,tratamiento,0,desktop,Mexico,299.96,2025-01-12
...,...,...,...,...,...,...,...
9995,exp_user_9995,tratamiento,0,mobile,Mexico,99.61,2025-01-27
9996,exp_user_9996,tratamiento,0,desktop,Argentina,209.82,2025-01-03
9997,exp_user_9997,tratamiento,0,mobile,Argentina,271.15,2025-02-26
9998,exp_user_9998,control,0,mobile,Colombia,216.11,2025-02-03
9999,exp_user_9999,tratamiento,0,mobile,Colombia,278.63,2025-06-13

In [82]:
# Asegurar que conversion sea binaria
df['conversion'] = df['convirtio'].astype(int)

df.head()

,id_usuario,variante,convirtio,dispositivo,pais,duracion_sesion,timestamp,conversion
0,exp_user_0,tratamiento,0,mobile,Argentina,114.41,2025-03-28,0
1,exp_user_1,tratamiento,0,desktop,Mexico,170.03,2025-01-15,0
2,exp_user_2,control,1,mobile,Colombia,140.21,2025-03-18,1
3,exp_user_3,tratamiento,0,mobile,Colombia,151.45,2025-06-03,0
4,exp_user_4,tratamiento,0,desktop,Mexico,299.96,2025-01-12,0

In [84]:
# calcular conversion por variante
conversion_rates = df.groupby('variante')['conversion'].mean()
conversion_rates

variante
control        0.156898
tratamiento    0.162860
Name: conversion, dtype: float64

In [86]:
from statsmodels.stats.proportion import proportions_ztest

# Conteo de conversiones por variante
conversions = df.groupby('variante')['conversion'].sum()

# Número total de usuarios por variante
n_obs = df.groupby('variante')['conversion'].count()

# Z-test
z_stat, p_value = proportions_ztest(count=conversions, nobs=n_obs, alternative='larger')

z_stat, p_value

(-0.8132782986429474, 0.7919707418044)

### Hipótesis nula (H₀): La conversión del tratamiento es igual a la del control.

### Hipótesis alternativa (H₁): La conversión del tratamiento es mayor.

### Resultado: p = 0.79 → No se rechaza H₀.

### Conclusión: La nueva UI no genera un impacto significativo en la conversión.

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - La prueba estadística está planteada de forma ordenada, con definición de hipótesis, cálculo de tasas de conversión por variante e interpretación del p-value para evaluar el impacto de la nueva UI.
</div>

---

## 🔹 Paso 6: Comunicar los resultados (Dashboard en BI)

🎯 **Objetivo**:  
Crear un dashboard que muestre de manera clara y visual los resultados del análisis de ventas, costos, marketing y conversión. 

Se usarán los CSVs limpios del Paso 1:

- `orders_clean.csv`  
- `catalog_clean.csv`  
- `marketing_clean.csv`

---

1️⃣ Preparación de los datos
1. Cargar los CSVs en Power BI o Tableau.
2. Revisar relaciones:
   - `orders.nombre_producto` → `catalog.nombre_producto`
   - `orders.fecha_pedido` → tabla de fechas (crear calendario para análisis temporal)
   - `orders.fecha_pedido` → `dim_fecha.date`
3. Crear columnas calculadas necesarias
4. Crear tabla de fechas para poder calcular comparaciones YTD, YoY o períodos anteriores (`Previous Year`, `Previous Month`).

---

2️⃣ Dashboard 1: Overview Ejecutivo
**KPIs principales a mostrar:**
- Revenue total
- Profit total
- Gasto total en marketing
- Ticket promedio
- Cantidad promedio de productos por orden

**Visualizaciones sugeridas:**
- Tarjetas KPI para revenue, profit y gasto marketing
- Gráfico de líneas: evolución mensual de revenue o profit
- Gráfico de líneas YTD
- Gráfico de barras: revenue y profit por producto o categoría

---

 3️⃣ Dashboard 2: Detalle / Drill-through  
**Objetivo:** Permitir explorar los datos desde el KPI general hasta cada orden o producto.

**Visualizaciones sugeridas:**
- Tabla detallada de órdenes con:
  - producto, cantidad, revenue, cost, profit
  - color condicional (profit negativo en rojo, positivo en verde)
- Gráfico de barras por producto con medida `cantidad vendida`
- Drill-through: seleccionar un producto y ver todos los pedidos relacionados
- Filtros por fecha, categoría de producto, etc

---

## 🚀 Entrega Final

Comparte el acceso a tu Dashboard para revisión.   
Puedes entregar el Dashboard utilizando **Power BI o Tableau**.

Incluye **uno de los siguientes**:

- 🔗 Link público del dashboard publicado en **Power BI Service o Tableau Public / Tableau Cloud**
- 🔗 Link de **Google Drive o OneDrive** con el archivo del proyecto (`.pbix`) y los 3 csvs limpios.


### 📎 Enlace del Dashboard

In [ ]:
# (Pega aquí tu link)
# link de power bi o tableau
# link de one drive / google drive

https://drive.google.com/file/d/1MqizzhIN4DSMSqTnfYedKN00bFZCJKTM/view?usp=sharing

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>Éxito</b> - El dashboard integra los KPIs principales y presenta una vista ejecutiva clara del desempeño comercial, complementando el análisis con visualizaciones de revenue, profit, marketing y detalle por producto.
</div>

<s>

<div class="alert alert-block alert-danger">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br>
<b>A resolver</b> ❗ - Falta incorporar el <b>dashboard</b> solicitado para comunicar los resultados principales del proyecto:

<ul>
  <li>Debe incluir visualizaciones claras de los KPIs del negocio, como revenue, costos, inversión en marketing y profit.</li>
  <li>También debe mostrar hallazgos clave del funnel, retención por cohortes y resultado del test estadístico.</li>
  <li>El dashboard es necesario para sintetizar el análisis y facilitar la toma de decisiones de negocio.</li>
</ul>

Agregar esta sección permitirá cerrar el proyecto con una presentación visual más completa y alineada con los objetivos planteados.










</div>